name: Repo root CI

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  format:
    name: Check format
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: task
        run: sleep 5

  ci_ok:
    name: OK
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: always()
    needs: [format]
    env:
      FAILURE: ${{ contains(join(needs.*.result, ','), 'failure') }}
      CANCELLED: ${{ contains(join(needs.*.result, ','), 'cancelled') }}
    steps:
      - name: Check for failure or cancelled jobs result
        shell: bash
        run: |
          echo "Failure: $FAILURE - Cancelled: $CANCELLED"
          if [ "$FAILURE" = "false" ] && [ "$CANCELLED" = "false" ]; then
            exit 0
          else
            exit 1
          fi
